In [1]:
import numpy as np
import pandas as pd
import glob
import re
import jieba

In [38]:
df = pd.read_csv("/Users/tsubomikaji/Desktop/弹幕/原始data/5.csv",header=None,error_bad_lines=False) 
df = df.iloc[:121442] #选择用户名和弹幕内容列
df = df.drop_duplicates() #删除重复行
df = df.dropna() #删除存在缺失值的行
df.columns = ["danmu"] #对字段进行命名
df
#机械压缩去重
def yasuo(st):
    for i in range(1,int(len(st)/2)+1):
        for j in range(len(st)):
            if st[j:j+2] == st[j+i:j+2*i]:
                k = j + i
                while st[k:k+i] == st[k+i:k+2*i] and k<len(st):   
                    k = k + i
                st = st[:j] + st[k:]    
    return st

b'Skipping line 1439: expected 1 fields, saw 2\nSkipping line 2315: expected 1 fields, saw 2\nSkipping line 2494: expected 1 fields, saw 2\n'

                       danmu
0                      ⭐⭐⭐⭐⭐
1                         暖心
2                         害怕
3            十个泪目九个怒，还有一个在狂怒
4                       怕了怕了
...                      ...
2988           借你吉言希望中考有个好成绩
2992      有点感动咋回事，先不给五星，给三星吧
2993                   我钉钉响了
2994              小学生嘴给我干净点！
2996  各位父老乡亲们，一定要坚定立场，表叛变！！！

[1376 rows x 1 columns]

In [39]:
#机械压缩去重
def yasuo(st):
    for i in range(1,int(len(st)/2)+1):
        for j in range(len(st)):
            if st[j:j+2] == st[j+i:j+2*i]:
                k = j + i
                while st[k:k+i] == st[k+i:k+2*i] and k<len(st):   
                    k = k + i
                st = st[:j] + st[k:]    
    return st
yasuo(st="啊啊啊啊啊啊啊")

'啊啊啊'

In [40]:
df["danmu"] = df["danmu"].apply(yasuo)
df

                       danmu
0                        ⭐⭐⭐
1                         暖心
2                         害怕
3            十个泪目九个怒，还有一个在狂怒
4                         怕了
...                      ...
2988           借你吉言希望中考有个好成绩
2992      有点感动咋回事，先不给五星，给三星吧
2993                   我钉钉响了
2994              小学生嘴给我干净点！
2996  各位父老乡亲们，一定要坚定立场，表叛变！！！

[1376 rows x 1 columns]

In [41]:
#特殊字符
df['danmu'] = df['danmu'].str.extract(r"([\u4e00-\u9fa5]+)")
df = df.dropna()
df

              danmu
1                暖心
2                害怕
3           十个泪目九个怒
4                怕了
5                加油
...             ...
2988  借你吉言希望中考有个好成绩
2992        有点感动咋回事
2993          我钉钉响了
2994      小学生嘴给我干净点
2996        各位父老乡亲们

[1320 rows x 1 columns]

In [42]:
#过短的弹幕
df = df[df["danmu"].apply(len)>=4]
df = df.dropna()
df

              danmu
3           十个泪目九个怒
6            高考不留遗憾
7              高考加油
14           卧槽太真实了
17             借你吉言
...             ...
2988  借你吉言希望中考有个好成绩
2992        有点感动咋回事
2993          我钉钉响了
2994      小学生嘴给我干净点
2996        各位父老乡亲们

[920 rows x 1 columns]

In [36]:
import csv

In [43]:
df.to_csv('/Users/tsubomikaji/Desktop/弹幕/原始data/clean5.csv')